#include "svg_writer.hpp"

#include <cmath>
#include <fstream>
#include <iostream>

namespace tree_svg {

auto SvgWriter::document(int width, int height, std::string_view body) -> std::string
{
    return std::format(
               "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
               "<svg\n"
               "   xmlns:dc=\"http://purl.org/dc/elements/1.1/\"\n"
               "   xmlns:cc=\"http://creativecommons.org/ns#\"\n"
               "   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
               "   xmlns:svg=\"http://www.w3.org/2000/svg\"\n"
               "   xmlns=\"http://www.w3.org/2000/svg\"\n"
               "   xmlns:xlink=\"http://www.w3.org/1999/xlink\"\n"
               "   width=\"{0}\"\n"
               "   height=\"{1}\"\n"
               "   viewBox=\"0 0 {0} {1}\"\n"
               "   version=\"1.1\"\n"
               "   id=\"svg8\">\n"
               "  <title id=\"title1\">Tree Top View</title>\n"
               "  <defs id=\"defs1\" />\n"
               "  <metadata id=\"metadata1\">\n"
               "    <rdf:RDF>\n"
               "      <cc:Work rdf:about=\"\">\n"
               "        <dc:format>image/svg+xml</dc:format>\n"
               "        <dc:type rdf:resource=\"http://purl.org/dc/dcmitype/StillImage\" />\n"
               "        <dc:title>Tree Top View</dc:title>\n"
               "        <dc:subject>\n"
               "          <rdf:Bag>\n"
               "            <rdf:li>tree</rdf:li>\n"
               "            <rdf:li>plant</rdf:li>\n"
               "            <rdf:li>nature</rdf:li>\n"
               "            <rdf:li>landscaping</rdf:li>\n"
               "          </rdf:Bag>\n"
               "        </dc:subject>\n"
               "        <dc:creator>\n"
               "          <cc:Agent>\n"
               "            <dc:title>https://github.com/jpenrici/SVG_Image_Tree/tree/master/SVG_Image_Tree_Top_View</dc:title>\n"
               "          </cc:Agent>\n"
               "        </dc:creator>\n"
               "        <cc:license rdf:resource=\"http://creativecommons.org/publicdomain/zero/1.0/\" />\n"
               "        <dc:description>SVG tree image in top view, generated automatically by a small C++ "
               "program. Leaves are clones of a single template shape, placed and rotated around the crown.</dc:description>\n"
               "      </cc:Work>\n"
               "      <cc:License rdf:about=\"http://creativecommons.org/publicdomain/zero/1.0/\">\n"
               "        <cc:permits rdf:resource=\"http://creativecommons.org/ns#Reproduction\" />\n"
               "        <cc:permits rdf:resource=\"http://creativecommons.org/ns#Distribution\" />\n"
               "        <cc:permits rdf:resource=\"http://creativecommons.org/ns#DerivativeWorks\" />\n"
               "      </cc:License>\n"
               "    </rdf:RDF>\n"
               "  </metadata>\n"
               "  <!-- Generated by create_svg_tree; edits will be overwritten if regenerated. -->\n"
               "{2}\n"
               "</svg>\n",
               width, height, body);
}

auto SvgWriter::shape(const Line &line, double curvature_degrees) -> std::string
{
    // A unique id such as "Leaf_3" or "Branch_12".
    const std::string id = std::format("{}_{}", line.label, shape_counter_++);

    const Point start = line.origin;
    const Point finish = line.end;
    const Point control_1{polar_x(start.x, line.length / 2.0, line.angle + curvature_degrees),
                          polar_y(start.y, line.length / 2.0, line.angle + curvature_degrees)};
    const Point control_2{polar_x(start.x, line.length / 2.0, line.angle - curvature_degrees),
                          polar_y(start.y, line.length / 2.0, line.angle - curvature_degrees)};

    return std::format(
               "     <path\n"
               "        id=\"{}\"\n"
               "        style=\"opacity:1.0;fill:#00a651;stroke:#1b5e20;stroke-width:0.5;stroke-opacity:1\"\n"
               "        d=\"M {},{} C {},{} {},{} {},{} Z\" />",
               id, start.x, start.y, control_1.x, control_1.y, control_2.x, control_2.y, finish.x, finish.y);
}

auto SvgWriter::clone(std::string_view reference_id, double angle_degrees, Point pivot, Point target)
-> std::string
{
    const std::string id = std::format("Clone_{}_{}", reference_id, clone_counter_++);

    const double a = angle_degrees * pi / 180.0;
    const double cos_a = std::cos(a);
    const double sin_a = std::sin(a);
    const double tx = target.x - pivot.x * cos_a + pivot.y * sin_a;
    const double ty = target.y - pivot.x * sin_a - pivot.y * cos_a;

    return std::format(
               "     <use\n"
               "        x=\"0\"\n"
               "        y=\"0\"\n"
               "        xlink:href=\"#{0}\"\n"
               "        id=\"{1}\"\n"
               "        transform=\"matrix({2},{3},{4},{5},{6},{7})\"\n"
               "        width=\"100%\"\n"
               "        height=\"100%\" />",
               reference_id, id, cos_a, sin_a, -sin_a, cos_a, tx, ty);
}

auto SvgWriter::save(std::string_view contents, std::string_view filename) -> bool
{
    std::string path{filename.empty() ? "out" : filename};
    if (!path.ends_with(".svg")) {
        path += ".svg";
    }

    std::ofstream file(path, std::ios::out | std::ios::trunc);
    if (!file) {
        std::cerr << std::format("error: could not open '{}' for writing\n", path);
        return false;
    }

    file << contents;
    if (!file) {
        std::cerr << std::format("error: failed while writing '{}'\n", path);
        return false;
    }

    return true;
}

} // namespace tree_svg
